[metadata]
name = collective.portletclass
version = 1.1
author = Laurence Rowe
author_email = lrowe@shuttlethread.com
license = GPL version 2
description = Add custom CSS classes to Plone portlet wrappers for flexible theming.
keywords = plone
url = https://github.com/collective/collective.portletclass
long_description = file: README.txt, CHANGES.txt
classifiers =
    Development Status :: 5 - Production/Stable
    Environment :: Web Environment
    Framework :: Plone
    Framework :: Plone :: Addon
    Framework :: Plone :: 5.0
    Framework :: Plone :: 6.0
    Framework :: Plone :: 6.1
    Programming Language :: Python
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Operating System :: OS Independent

platforms = Any

[options]
zip_safe = False
install_requires =
    collective.monkeypatcher
    plone.app.portlets
    plone.browserlayer
    setuptools
    z3c.jbot
include_package_data = True

python_requires = >=2.7
package_dir =
     = src
packages = find:

[options.packages.find]
where = src

[options.extras_require]
test =

[options.entry_points]
z3c.autoinclude.plugin =
    target = plone